# Generated by Django 5.1.1 on 2024-10-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
    ]
