# Generated by Django 5.1.1 on 2024-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0002_alter_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
