# Generated by Django 5.1.1 on 2024-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
