# Generated by Django 5.1.1 on 2024-10-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ширина'),
        ),
    ]
