# Generated by Django 5.1.1 on 2024-10-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0005_product_high_product_length_product_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
