# Generated by Django 5.1.1 on 2024-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
    ]
