# Generated by Django 5.1.1 on 2024-10-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0011_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('total_price', models.FloatField(default=0, verbose_name='Сумма заказа')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'Истории заказов',
            },
        ),
        migrations.CreateModel(
            name='SaveOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500, verbose_name='Товар')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('product_price', models.FloatField(default=0, verbose_name='Цена товара')),
                ('final_price', models.FloatField(default=0, verbose_name='Общая сумма')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Фото товара')),
                ('color_name', models.CharField(max_length=50, verbose_name='Цвет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loft.saveorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История заказанного товара',
                'verbose_name_plural': 'История заказанных товаров',
            },
        ),
    ]
