# Generated by Django 5.1.1 on 2024-10-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0012_saveorder_saveorderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом/Корпус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.CreateModel(
            name='SaveCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время заказа')),
                ('total_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Итоговая сумма заказа')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Сохраненный заказ',
                'verbose_name_plural': 'Сохраненные заказы',
            },
        ),
        migrations.CreateModel(
            name='SaveCardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказанный товар')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во')),
                ('product_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена товара')),
                ('final_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Итоговая цена товара')),
                ('discount_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Скидочная цена товара')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='save_card_product/')),
                ('color_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('state', models.CharField(blank=True, max_length=150, null=True, verbose_name='Статус заказа')),
                ('save_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loft.savecard', verbose_name='Сохраненный заказ')),
            ],
            options={
                'verbose_name': 'Сохраненный заказанный товар',
                'verbose_name_plural': 'Сохраненные заказанные товары',
            },
        ),
    ]
