# Generated by Django 5.1.1 on 2024-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0015_remove_cartproduct_cart_remove_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderproduct',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='saveorderproduct',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото товара'),
        ),
    ]
