# Generated by Django 5.1.1 on 2024-10-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0016_saveorderproduct_state_alter_saveorderproduct_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderproduct',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Скидочная цена товара'),
        ),
    ]
